replicaCount: 1

image:
  repository: faizan00parvez/deploywatch
  tag: e2b2c2c618bd224837877c591785ad0062a6b1ce
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70