replicaCount: 1

image:
  repository: faizan00parvez/deploywatch
  tag: 18ecc8cdea03d6692b2eb10d76615dbd9327e1db
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70